<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $report_title }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #333; }
        h1 { font-size: 22px; margin-bottom: 5px; }
        h4 { margin-top: 0; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        th, td { padding: 8px 10px; border: 1px solid #ddd; }
        th { background: #f4f4f4; text-transform: uppercase; font-size: 12px; }
        td { font-size: 13px; }
        .header { display: flex; justify-content: space-between; align-items: center; }
        .meta { font-size: 12px; color: #777; margin-top: 10px; }
    </style>
</head>
<body>

    <div class="header">
        <div>
            <h1>{{ $report_title }}</h1>
            <h4>Invensure</h4>
        </div>
    </div>

    <div class="meta">
        <p>Generated: {{ $generated_date }}</p>
        <p>Generated by: {{ $generated_by }}</p>
    </div>

    <h3 style="margin-top:20px;">Inventory Status</h3>

    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($metrics as $metric)
                <tr>
                    <td>{{ $metric[0] }}</td>
                    <td>{{ $metric[1] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

     <h3 style="margin-top:20px;">Logistics Status</h3>

    <table>
        <thead>
            <tr>
                <th>Metric</th>
                <th>Details</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($logistics as $item)
                <tr>
                    <td>{{ $item[0] }}</td>
                    <td>{{ $item[1] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

</body>
</html>
