<x-app-layout>

    @include('layouts.sidebar')

    <div class="py-8 w-full">
        <div class="w-full px-2 lg:px-4">
            <div class=" overflow-hidden lg:p-6">

                <div class="flex flex-col lg:flex-row  lg:items-center lg:justify-between">
                    <div class="flex flex-col">
                        <h1 class="text-2xl font-bold text-zinc-900">Summary Report</h1>
                        <h4 class="text-zinc-700">Invensure</h4>
                    </div>
                </div>
                <div class="text-sm text-gray-400 flex flex-col mt-5">
                    <span>Generated: October 28, 2025</span>
                    <span>Generated by: Kasandra Bumagat</span>
                </div>

                <div class="mt-10">
                    <span class="text-gray-600">Inventory Status</span>
                    <div class="mt-5 bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm">
                        <table class="min-w-full text-sm text-gray-700">
                            <thead class="bg-gray-100 text-gray-700 uppercase text-xs tracking-wider">
                                <tr>
                                    <th class="py-3 px-4 text-left font-medium">Metric</th>
                                    <th class="py-3 px-4 text-left font-medium">Details</th>

                                </tr>
                            </thead>
                            <tbody class="divide-y divide-gray-200">
                                <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">All Warehouse: Total Products</td>
                                    <td class="py-3 px-4">222</td>

                                </tr>

                                <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">Low Stock Items</td>
                                    <td class="py-3 px-4">123</td>
                                </tr>
                                <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">Pending Orders</td>
                                    <td class="py-3 px-4">514</td>
                                </tr>
                                <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">Reject and Returns</td>
                                    <td class="py-3 px-4">1</td>
                                </tr>
                                 <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total Inventory (Head/Pack)</td>
                                    <td class="py-3 px-4">35,141</td>
                                </tr>
                                 <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total Inventory (Kilogram)</td>
                                    <td class="py-3 px-4">33,305</td>
                                </tr>
                                 <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total QTY Issued (Head/Pack)</td>
                                    <td class="py-3 px-4">35,141</td>
                                </tr>
                                 <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total QTY Issued (Kilogram)</td>
                                    <td class="py-3 px-4">33,305</td>
                                </tr>
                                 <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total Available Balance (Head/Pack)</td>
                                    <td class="py-3 px-4">35,141</td>
                                </tr>
                                 <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total Available Balance (Kilogram)</td>
                                    <td class="py-3 px-4">33,305</td>
                                </tr>
                                <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total Available Stock</td>
                                    <td class="py-3 px-4">555</td>
                                </tr>
                                <tr class="hover:bg-gray-50 transition">
                                    <td class="py-3 px-4">PCSI Warehouse: Total Expiring Soon</td>
                                    <td class="py-3 px-4">0</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>


            </div>
        </div>
    </div>
</x-app-layout>
