<div class="bg-gray-50 rounded-lg p-6 border-2 border-gray-200 w-full text-black">
    <div class="flex justify-between items-center">
        <div>
            <h1 class="text-xl text-gray-800 font-semibold">Reports</h1>
            <p class="text-sm text-gray-500">View and generate supply chain reports</p>
        </div>

        <form action="{{ route('reports.generate') }}" method="GET" x-data="{ loading: false }" @submit="loading = true">
            <button type="submit"
                class="bg-orange-500 px-4 py-2 flex items-center gap-3 rounded-md text-gray-50 text-sm hover:bg-orange-400 transition duration-200 ease-in-out"
                :disabled="loading">
                <template x-if="loading">
                    <x-lucide-loader class="h-4 w-4 animate-spin" />
                </template>

                <template x-if="!loading">
                    <x-lucide-sparkles class="h-4 w-4" />
                </template>

                <span x-text="loading ? 'Generating...' : 'Generate Report'"></span>
            </button>
        </form>


    </div>

    <div class="mt-5">
        {{-- <select
            class="w-full max-w-xs px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent text-sm">
            <option disabled selected>Select Report Type</option>
            <option>Inventory Reports</option>
            <option>Finance Reports</option>
            <option>Sales Reports</option>
        </select> --}}

        <!-- Table container with border + rounded corners -->
        <div class="mt-5 bg-white border border-gray-200 rounded-xl  shadow-sm">
            <table class="min-w-full text-sm text-gray-700">
                <thead class="bg-gray-100 text-gray-700 uppercase rounded-xl text-xs tracking-wider">
                    <tr>
                        <th class="py-3 px-4 text-left font-medium rounded-tl-xl">Generated By</th>
                        <th class="py-3 px-4 text-left font-medium">Type</th>
                        <th class="py-3 px-4 text-left font-medium">Warehouse</th>
                        <th class="py-3 px-4 text-left font-medium">Generated</th>
                        <th class="py-3 px-4 text-left font-medium">Size</th>
                        <th class="py-3 px-4 text-center font-medium rounded-tr-xl">Actions</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-200">
                    @foreach ($reportsHistory as $history)
                        <tr class="hover:bg-gray-50 transition">
                            <td class="py-3 px-4">{{ $history->generated_by }}</td>
                            <td class="py-3 px-4">PDF</td>
                            <td class="py-3 px-4">{{ $history->warehouse }}</td>
                            <td class="py-3 px-4">
                                {{ \Carbon\Carbon::parse($history->generated_at)->format('F d, Y h:i A') }}</td>
                            <td class="py-3 px-4">{{ $history->file_size }}</td>
                            <td class="py-3 px-4 text-center">
                                <div class="dropdown dropdown-end">
                                    <!-- Ellipsis button -->
                                    <button tabindex="0" class="p-2 hover:bg-orange-500 hover:text-white rounded-lg">
                                        <x-lucide-ellipsis-vertical class="h-4 w-4" />
                                    </button>

                                    <!-- Dropdown menu -->
                                    <ul tabindex="0"
                                        class="dropdown-content menu p-2 shadow bg-white rounded-box w-40 z-[99]">
                                        <li class="hover:bg-gray-200 rounded-md">
                                            @php
                                                // Extract the file ID from the Google Drive URL
                                                preg_match('/id=([^&]+)/', $history->file_url, $matches);
                                                $fileId = $matches[1] ?? null;
                                                $viewUrl = $fileId
                                                    ? "https://drive.google.com/file/d/{$fileId}/view"
                                                    : '#';
                                            @endphp
                                            <a href="{{ $viewUrl }}" target="_blank"
                                                class="flex items-center gap-2">
                                                <x-lucide-eye class="h-4 w-4" />
                                                <span>View</span>
                                            </a>
                                        </li>
                                        <li class="hover:bg-gray-200 rounded-md">
                                            <a href="{{ $history->file_url }}" class="flex items-center gap-2">
                                                <x-lucide-download class="h-4 w-4" />
                                                <span>Download</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>

                        </tr>
                    @endforeach


                </tbody>
            </table>
        </div>
    </div>
</div>
