<div class="bg-gray-50 rounded-lg p-6 border-2 border-gray-200 w-full text-black">
    <div class="flex justify-between items-center">
        <div>
            <h1 class="text-xl text-gray-800 font-semibold">Reports</h1>
            <p class="text-sm text-gray-500">View and generate supply chain reports</p>
        </div>

        <form action="{{ route('reports.generate') }}" method="GET" x-data="{ loading: false }" @submit="loading = true">
            <button type="submit"
                class="bg-orange-500 px-4 py-2 flex items-center gap-3 rounded-md text-gray-50 text-sm hover:bg-orange-400 transition duration-200 ease-in-out"
                :disabled="loading">
                <template x-if="loading">
                    <x-lucide-loader class="h-4 w-4 animate-spin" />
                </template>

                <template x-if="!loading">
                    <x-lucide-sparkles class="h-4 w-4" />
                </template>

                <span x-text="loading ? 'Generating...' : 'Generate Report'"></span>
            </button>
        </form>


    </div>

    <div class="mt-5 w-full">
        <div x-data="{
            reports: [],
            page: 1,
            lastPage: 1,
            async loadPage(p = 1) {
                const res = await fetch(`/reports-json?page=${p}`);
                const data = await res.json();
                this.reports = data.data;
                this.page = data.current_page;
                this.lastPage = data.last_page;
            }
        }" x-init="loadPage()"
            class="">
            <div class="mt-5 bg-white border border-gray-200 rounded-xl shadow-sm">


                <table class="min-w-full text-sm text-gray-700">
                    <thead class="bg-gray-100 text-gray-700 uppercase rounded-xl text-xs tracking-wider">
                        <tr>
                            <th class="py-3 px-4 text-left font-medium rounded-tl-xl">Generated By</th>
                            <th class="py-3 px-4 text-left font-medium">Type</th>
                            <th class="py-3 px-4 text-left font-medium">Warehouse</th>
                            <th class="py-3 px-4 text-left font-medium">Generated</th>
                            <th class="py-3 px-4 text-left font-medium">Size</th>
                            <th class="py-3 px-4 text-center font-medium rounded-tr-xl">Actions</th>
                        </tr>
                    </thead>

                    <tbody class="divide-y divide-gray-200">
                        <template x-for="history in reports" :key="history.id">
                            <tr class="hover:bg-gray-50 transition">
                                <td class="py-3 px-4" x-text="history.generated_by"></td>
                                <td class="py-3 px-4">PDF</td>
                                <td class="py-3 px-4" x-text="history.warehouse"></td>
                                <td class="py-3 px-4" x-text="new Date(history.generated_at).toLocaleString()"></td>
                                <td class="py-3 px-4" x-text="history.file_size"></td>
                                <td class="py-3 px-4 text-center">
                                    <div class="dropdown dropdown-end">
                                        <button tabindex="0"
                                            class="p-2 hover:bg-orange-500 hover:text-white rounded-lg">
                                            <x-lucide-ellipsis-vertical class="h-4 w-4" />
                                        </button>
                                        <ul tabindex="0"
                                            class="dropdown-content menu p-2 shadow bg-white rounded-box w-40 z-[99]">
                                            <template x-if="history.file_url">
                                                <li class="hover:bg-gray-200 rounded-md">
                                                    <a :href="`https://drive.google.com/file/d/${history.file_url.match(/id=([^&]+)/)?.[1]}/view`"
                                                        target="_blank" class="flex items-center gap-2">
                                                        <x-lucide-eye class="h-4 w-4" />
                                                        <span>View</span>
                                                    </a>
                                                </li>
                                            </template>
                                            <li class="hover:bg-gray-200 rounded-md">
                                                <a :href="history.file_url" class="flex items-center gap-2">
                                                    <x-lucide-download class="h-4 w-4" />
                                                    <span>Download</span>
                                                </a>
                                            </li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        </template>
                    </tbody>
                </table>
            </div>

           
            <!-- Pagination -->
            <div class="flex justify-end mt-4 space-x-1 mb-5 mr-5">
                <button :disabled="page === 1" @click="loadPage(page-1)"
                    class="px-3 py-1 border bg-white rounded-l-md hover:bg-gray-100 disabled:opacity-50">Previous</button>

                <template x-for="p in lastPage" :key="p">
                    <button @click="loadPage(p)"
                        :class="page === p ? 'bg-orange-500 text-white' : 'bg-white border hover:bg-gray-100'"
                        class="px-3 py-1 border" x-text="p"></button>
                </template>

                <button :disabled="page === lastPage" @click="loadPage(page+1)"
                    class="px-3 py-1 border bg-white rounded-r-md hover:bg-gray-100 disabled:opacity-50">Next</button>
            </div>
        </div>

    </div>
</div>
